INCLUDE Contest.inc

.data
; ----Local----

; ----Global----

; misc
PUBLIC gLevel
PUBLIC gGold
PUBLIC gGameState

gLevel		DWORD 1
gGold		DWORD 0
gGameState	DWORD 1

; player
PUBLIC gPlayerHP
PUBLIC gPlayerMaxHP
PUBLIC gPlayerATK 
PUBLIC gPlayerDEF
PUBLIC gHealPots
PUBLIC gHealing

gPlayerHP     DWORD PLAYER_BASE_HP
gPlayerMaxHP  DWORD PLAYER_BASE_HP
gPlayerATK    DWORD PLAYER_BASE_ATK
gPlayerDEF    DWORD PLAYER_BASE_DEF
gHealPots	  DWORD PLAYER_BASE_HEAL
gHealing	  DWORD HEAL_MIN

; enemy
PUBLIC gEnemyHP 
PUBLIC gEnemyMaxHP
PUBLIC gEnemyATK
PUBLIC gEnemyDEF

gEnemyHP      DWORD ENEMY_BASE_HP
gEnemyMaxHP   DWORD ENEMY_BASE_HP
gEnemyATK     DWORD ENEMY_BASE_ATK
gEnemyDEF     DWORD ENEMY_BASE_DEF

; shop
PUBLIC gShopHP
PUBLIC gShopATK
PUBLIC gShopDEF
PUBLIC gShopHPot

gShopHP		DWORD PLAYER_UPGRADE_HP_PRICE
gShopATK	DWORD PLAYER_UPGRADE_ATK_PRICE
gShopDEF	DWORD PLAYER_UPGRADE_DEF_PRICE
gShopHPot	DWORD PLAYER_UPGRADE_HPot_PRICE


.code
PUBLIC main
main PROC
Battle:
	INVOKE BattleLoop
	MOV EAX, gGameState
	CMP EAX, 0
	JZ Quit
	INC gLevel

	INVOKE Shop
	JMP Battle
Quit:
	exit
main ENDP
END main